In [5]:
import pandas as pd
import sys
import os

sys.path.append(
    os.path.abspath("..")
)
from src.hypothesis_tests import *
from src.data_loader import load_data

In [10]:
df = load_data("../data/MachineLearningRating_v3.txt")
df.head()

c:\KAIM_projects\insurance-risk-analytics\src\data_loader.py:5: DtypeWarning: Columns (0: CapitalOutstanding, 1: CrossBorder) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, sep="|")

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [11]:
df = create_kpis(df)

results = []

chi, p = chi_square_test(df, "Province")
results.append(["Province", "chi-square", p, p < 0.05])

chi, p = chi_square_test(df, "PostalCode")
results.append(["ZipCode", "chi-square", p, p < 0.05])

g = df.groupby("Gender")["has_claim"].mean().index
if len(g) >= 2:
    a, b = g[0], g[1]
    z, p = z_test_proportions(df, "Gender", a, b)
    results.append(["Gender", "z-test", p, p < 0.05])

df["margin"] = df["TotalPremium"] - df["TotalClaims"]

zip_codes = df["PostalCode"].dropna().unique()
if len(zip_codes) >= 2:
    a, b = zip_codes[0], zip_codes[1]
    t, p = t_test_groups(df, "PostalCode", "margin", a, b)
    results.append(["ZipCode Margin", "t-test", p, p < 0.05])

pd.DataFrame(results, columns=["Feature", "Test", "p_value", "reject_H0"])

          Feature        Test       p_value  reject_H0
0        Province  chi-square  5.925511e-19       True
1         ZipCode  chi-square  3.152172e-30       True
2          Gender      z-test  8.404941e-01      False
3  ZipCode Margin      t-test  6.630316e-01      False